workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: docker
    repo: plugins/sftp-cache
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Sftp Cache
  desc: Cache and restore your build environment
  type: cache
  image: plugins/sftp-cache
  labels:
    - cache
    - sftp
    - ssh
