workspace:
  base: /srv/app
  path: src/github.com/appleboy/drone-sftp-cache

pipeline:  clone:
    image: plugins/git
    tags: true

  # restore the cache from an sftp server
  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ .glide, vendor ]
    ignore_branch: true

  test:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
      GOPATH: /srv/app
    commands:
      - make dep_install
      - make vet
      - make lint
      - coverage all
      - make coverage
      - make build
      # build binary for docker image
      - make static_build
    when:
      event: [ push, tag, pull_request ]

  # deploy image from tag event
  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  # deploy image from master branch
  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  # rebuild the cache on the sftp server
  rebuild_cache:
    image: appleboy/drone-sftp-cache
    rebuild: true
    mount: [ .glide, vendor ]
    ignore_branch: true
    when:
      branch: master
